### ISSUE TITLE
☂️ Umbrella Issue: API

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org-cloudflare-worker#7]
Approach for extending the API:

- Add contract tests that define newly needed endpoints, see [`__tests-pacts__/api.ts`](https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/__tests-pacts__/api.ts)
- Implement the GraphQL Proxy, see [`src/api`](https://github.com/serlo/serlo.org-cloudflare-worker/tree/master/src/api)
- Publish contract tests and add the new endpoints to https://github.com/serlo/serlo.org

Things to consider: 
- The new endpoints in https://github.com/serlo/serlo.org should be prefixed with `/api` (e.g. `/api/license/<id>`. Prefer GET requests where possible (i.e. prefer URL parameters over POST body)
- Limit the required requests (e.g. fetch nested data that requires new requests only if it is requested)

Status:
- [ ] Uuid
  - [ ] Entity
    - [x] Article
    - [ ] ... other entity types
  - [ ] EntityRevision
     - [x] ArticleRevision
     - [ ] ... other entity revision types
  - [x] Page
  - [ ] PageRevision
  - [ ] ... other uuid discriminators
- [x] License
- [ ] ... other
